python offline_dqn.py --config configs/2016.yaml
python offline_dqn.py --config configs/2017.yaml
python offline_dqn.py --config configs/2018.yaml
python offline_dqn.py --config configs/2019.yaml
python offline_dqn.py --config configs/2020.yaml
python offline_dqn.py --config configs/2021.yaml
python offline_dqn.py --config configs/2022.yaml
python offline_dqn.py --config configs/2023.yaml
python offline_dqn.py --config configs/2024.yaml
python offline_dqn.py --config configs/2025.yaml