train_start_season: 2011
train_end_season: 2021
test_season: 2022
epochs: 50
cql_alpha: 10
lr: 0.0003
batch_size: 512
gamma: 1.0
hidden_dim: 128
target_update_freq: 10000
checkpoint_path: models/undiscounted/2022/
device: cuda
start_seed: 0
end_seed: 29
data: data/offline_rl.parquet
